#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Mon Dec 08 18:39:51 2008

import wx
from Loteria import Loteria

if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    janelaPrincipal = Loteria(None, -1, "")
    app.SetTopWindow(janelaPrincipal)
    janelaPrincipal.Show()
    app.MainLoop()
