#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Mon Dec 08 16:39:08 2008

import wx

# begin wxGlade: extracode
mAdicionar = 1001
mRemover = 1002
mSair = 1003
# end wxGlade



class Adicionar(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Adicionar.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.ck00 = wx.CheckBox(self, -1, "00")
        self.ck01 = wx.CheckBox(self, -1, "01")
        self.ck02 = wx.CheckBox(self, -1, "02")
        self.ck03 = wx.CheckBox(self, -1, "03")
        self.ck04 = wx.CheckBox(self, -1, "04")
        self.ck05 = wx.CheckBox(self, -1, "05")
        self.ck06 = wx.CheckBox(self, -1, "06")
        self.ck07 = wx.CheckBox(self, -1, "07")
        self.ck08 = wx.CheckBox(self, -1, "08")
        self.ck09 = wx.CheckBox(self, -1, "09")
        self.ck10 = wx.CheckBox(self, -1, "10")
        self.ck11 = wx.CheckBox(self, -1, "11")
        self.ck12 = wx.CheckBox(self, -1, "12")
        self.ck13 = wx.CheckBox(self, -1, "13")
        self.ck14 = wx.CheckBox(self, -1, "14")
        self.ck15 = wx.CheckBox(self, -1, "15")
        self.ck16 = wx.CheckBox(self, -1, "16")
        self.ck17 = wx.CheckBox(self, -1, "17")
        self.ck18 = wx.CheckBox(self, -1, "18")
        self.ck19 = wx.CheckBox(self, -1, "19")
        self.ck20 = wx.CheckBox(self, -1, "20")
        self.ck21 = wx.CheckBox(self, -1, "21")
        self.ck22 = wx.CheckBox(self, -1, "22")
        self.ck23 = wx.CheckBox(self, -1, "23")
        self.ck24 = wx.CheckBox(self, -1, "24")
        self.ck25 = wx.CheckBox(self, -1, "25")
        self.ck26 = wx.CheckBox(self, -1, "26")
        self.ck27 = wx.CheckBox(self, -1, "27")
        self.ck28 = wx.CheckBox(self, -1, "28")
        self.ck29 = wx.CheckBox(self, -1, "29")
        self.ck30 = wx.CheckBox(self, -1, "30")
        self.ck31 = wx.CheckBox(self, -1, "31")
        self.ck32 = wx.CheckBox(self, -1, "32")
        self.ck33 = wx.CheckBox(self, -1, "33")
        self.ck34 = wx.CheckBox(self, -1, "34")
        self.ck35 = wx.CheckBox(self, -1, "35")
        self.ck36 = wx.CheckBox(self, -1, "36")
        self.ck37 = wx.CheckBox(self, -1, "37")
        self.ck38 = wx.CheckBox(self, -1, "38")
        self.ck39 = wx.CheckBox(self, -1, "39")
        self.ck40 = wx.CheckBox(self, -1, "40")
        self.ck41 = wx.CheckBox(self, -1, "41")
        self.ck42 = wx.CheckBox(self, -1, "42")
        self.ck43 = wx.CheckBox(self, -1, "43")
        self.ck44 = wx.CheckBox(self, -1, "44")
        self.ck45 = wx.CheckBox(self, -1, "45")
        self.ck46 = wx.CheckBox(self, -1, "46")
        self.ck47 = wx.CheckBox(self, -1, "47")
        self.ck48 = wx.CheckBox(self, -1, "48")
        self.ck49 = wx.CheckBox(self, -1, "49")
        self.bLimpar = wx.Button(self, -1, "Limpar")
        self.bSalvar = wx.Button(self, -1, "Salvar")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Adicionar.__set_properties
        self.SetTitle("Adicionar Bilhete")
        _icon = wx.EmptyIcon()
        _icon.CopyFromBitmap(wx.Bitmap("C:\\Users\\Bruno\\Documents\\Trabalhos\\Loteria\\icone.ico", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        self.ck00.SetMinSize((50,50))
        self.ck00.SetBackgroundColour(wx.Colour(208, 208, 208))
        self.ck01.SetBackgroundColour(wx.Colour(208, 208, 208))
        self.ck02.SetBackgroundColour(wx.Colour(208, 208, 208))
        self.ck03.SetBackgroundColour(wx.Colour(208, 208, 208))
        self.ck04.SetBackgroundColour(wx.Colour(208, 208, 208))
        self.ck05.SetBackgroundColour(wx.Colour(208, 208, 208))
        self.ck06.SetBackgroundColour(wx.Colour(208, 208, 208))
        self.ck07.SetBackgroundColour(wx.Colour(208, 208, 208))
        self.ck08.SetBackgroundColour(wx.Colour(208, 208, 208))
        self.ck09.SetBackgroundColour(wx.Colour(208, 208, 208))
        self.ck10.SetBackgroundColour(wx.Colour(187, 187, 187))
        self.ck11.SetBackgroundColour(wx.Colour(187, 187, 187))
        self.ck12.SetBackgroundColour(wx.Colour(187, 187, 187))
        self.ck13.SetBackgroundColour(wx.Colour(187, 187, 187))
        self.ck14.SetBackgroundColour(wx.Colour(187, 187, 187))
        self.ck15.SetBackgroundColour(wx.Colour(187, 187, 187))
        self.ck16.SetBackgroundColour(wx.Colour(187, 187, 187))
        self.ck17.SetBackgroundColour(wx.Colour(187, 187, 187))
        self.ck18.SetBackgroundColour(wx.Colour(187, 187, 187))
        self.ck19.SetBackgroundColour(wx.Colour(187, 187, 187))
        self.ck20.SetBackgroundColour(wx.Colour(208, 208, 208))
        self.ck21.SetBackgroundColour(wx.Colour(208, 208, 208))
        self.ck22.SetBackgroundColour(wx.Colour(208, 208, 208))
        self.ck23.SetBackgroundColour(wx.Colour(208, 208, 208))
        self.ck24.SetBackgroundColour(wx.Colour(208, 208, 208))
        self.ck25.SetBackgroundColour(wx.Colour(208, 208, 208))
        self.ck26.SetBackgroundColour(wx.Colour(208, 208, 208))
        self.ck27.SetBackgroundColour(wx.Colour(208, 208, 208))
        self.ck28.SetBackgroundColour(wx.Colour(208, 208, 208))
        self.ck29.SetBackgroundColour(wx.Colour(208, 208, 208))
        self.ck30.SetBackgroundColour(wx.Colour(187, 187, 187))
        self.ck30.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.ck31.SetBackgroundColour(wx.Colour(187, 187, 187))
        self.ck31.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.ck32.SetBackgroundColour(wx.Colour(187, 187, 187))
        self.ck32.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.ck33.SetBackgroundColour(wx.Colour(187, 187, 187))
        self.ck33.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.ck34.SetBackgroundColour(wx.Colour(187, 187, 187))
        self.ck34.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.ck35.SetBackgroundColour(wx.Colour(187, 187, 187))
        self.ck35.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.ck36.SetBackgroundColour(wx.Colour(187, 187, 187))
        self.ck36.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.ck37.SetBackgroundColour(wx.Colour(187, 187, 187))
        self.ck37.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.ck38.SetBackgroundColour(wx.Colour(187, 187, 187))
        self.ck38.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.ck39.SetBackgroundColour(wx.Colour(187, 187, 187))
        self.ck39.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.ck40.SetBackgroundColour(wx.Colour(208, 208, 208))
        self.ck40.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.ck41.SetBackgroundColour(wx.Colour(208, 208, 208))
        self.ck41.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.ck42.SetBackgroundColour(wx.Colour(208, 208, 208))
        self.ck42.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.ck43.SetBackgroundColour(wx.Colour(208, 208, 208))
        self.ck43.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.ck44.SetBackgroundColour(wx.Colour(208, 208, 208))
        self.ck44.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.ck45.SetBackgroundColour(wx.Colour(208, 208, 208))
        self.ck45.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.ck46.SetBackgroundColour(wx.Colour(208, 208, 208))
        self.ck46.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.ck47.SetBackgroundColour(wx.Colour(208, 208, 208))
        self.ck47.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.ck48.SetBackgroundColour(wx.Colour(208, 208, 208))
        self.ck48.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.ck49.SetBackgroundColour(wx.Colour(208, 208, 208))
        self.ck49.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.bLimpar.SetToolTipString("Limpa o bilhete.")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Adicionar.__do_layout
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.GridSizer(10, 10, 0, 0)
        grid_sizer_1.Add(self.ck00, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck01, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck02, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck03, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck04, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck05, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck06, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck07, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck08, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck09, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck10, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck11, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck12, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck13, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck14, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck15, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck16, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck17, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck18, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck19, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck20, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck21, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck22, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck23, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck24, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck25, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck26, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck27, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck28, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck29, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck30, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck31, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck32, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck33, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck34, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck35, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck36, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck37, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck38, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck39, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck40, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck41, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck42, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck43, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck44, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck45, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck46, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck47, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck48, 0, wx.ALL|wx.EXPAND, 3)
        grid_sizer_1.Add(self.ck49, 0, wx.ALL|wx.EXPAND, 3)
        sizer_2.Add(grid_sizer_1, 4, wx.EXPAND, 0)
        sizer_3.Add(self.bLimpar, 0, wx.TOP|wx.BOTTOM|wx.ALIGN_CENTER_HORIZONTAL, 10)
        sizer_3.Add(self.bSalvar, 0, wx.TOP|wx.BOTTOM|wx.ALIGN_CENTER_HORIZONTAL, 10)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_2)
        sizer_2.Fit(self)
        self.Layout()
        self.Centre()
        # end wxGlade

# end of class Adicionar


class Loteria(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Loteria.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        
        # Menu Bar
        self.menu = wx.MenuBar()
        self.jogos = wx.Menu()
        self.mAdicionar = wx.MenuItem(self.jogos, mAdicionar, "Adicionar", "Adiciona novo bilhete.", wx.ITEM_NORMAL)
        self.jogos.AppendItem(self.mAdicionar)
        self.mRemover = wx.MenuItem(self.jogos, mRemover, "Remover", "Remove Bilhete.", wx.ITEM_NORMAL)
        self.jogos.AppendItem(self.mRemover)
        self.jogos.AppendSeparator()
        self.mSair = wx.MenuItem(self.jogos, mSair, "Sair", "Encerra Aplicativo.", wx.ITEM_NORMAL)
        self.jogos.AppendItem(self.mSair)
        self.menu.Append(self.jogos, "Jogos")
        self.SetMenuBar(self.menu)
        # Menu Bar end
        self.barrastatus = self.CreateStatusBar(1, 0)
        self.painel = wx.Panel(self, -1)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_MENU, self.Adicionar, self.mAdicionar)
        self.Bind(wx.EVT_MENU, self.Sair, self.mSair)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Loteria.__set_properties
        self.SetTitle("LotoMania")
        _icon = wx.EmptyIcon()
        _icon.CopyFromBitmap(wx.Bitmap("C:\\Users\\Bruno\\Documents\\Trabalhos\\Loteria\\icone.ico", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        self.barrastatus.SetStatusWidths([-1])
        # statusbar fields
        barrastatus_fields = ["Lotomania"]
        for i in range(len(barrastatus_fields)):
            self.barrastatus.SetStatusText(barrastatus_fields[i], i)
        self.painel.SetMinSize((329, 241))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Loteria.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(self.painel, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        self.Centre()
        # end wxGlade

    def Adicionar(self,event):
        frame_1 = Loteria(None, -1, "")
        app.SetTopWindow(frame_1)
        frame_1.Show()
        app.MainLoop()

    def Sair(self, event): # wxGlade: Loteria.<event_handler>
        self.Close(True)  # Close the frame.

    def Adicionar(self, event): # wxGlade: Loteria.<event_handler>
        tela = Adicionar(None, -1, "")
        app.SetTopWindow(tela)
        tela.Show()
        

# end of class Loteria

if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = Loteria(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
