#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Fri Dec 05 17:46:25 2008

import wx

# begin wxGlade: extracode
# end wxGlade



class LotoMania(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: LotoMania.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        
        # Menu Bar
        self.LotoMania_menubar = wx.MenuBar()
        self.Jogos = wx.Menu()
        self.LotoMania_menubar.Append(self.Jogos, "Jogos")
        wxglade_tmp_menu = wx.Menu()
        self.LotoMania_menubar.Append(wxglade_tmp_menu, "Sair")
        self.SetMenuBar(self.LotoMania_menubar)
        # Menu Bar end
        self.LotoMania_statusbar = self.CreateStatusBar(1, wx.ST_SIZEGRIP)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: LotoMania.__set_properties
        self.SetTitle("LotoMania")
        _icon = wx.EmptyIcon()
        _icon.CopyFromBitmap(wx.Bitmap("C:\\Documents and Settings\\bruno\\Desktop\\LotoMania\\icone.ico", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        self.LotoMania_statusbar.SetStatusWidths([-1])
        # statusbar fields
        LotoMania_statusbar_fields = ["LotoMania"]
        for i in range(len(LotoMania_statusbar_fields)):
            self.LotoMania_statusbar.SetStatusText(LotoMania_statusbar_fields[i], i)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: LotoMania.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

# end of class LotoMania


class Menu(wx.MenuBar):
    def __init__(self, *args, **kwds):
        # content of this block not found: did you rename this class?
        pass

    def __set_properties(self):
        # content of this block not found: did you rename this class?
        pass

    def __do_layout(self):
        # content of this block not found: did you rename this class?
        pass

# end of class Menu


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    LotoMania = LotoMania(None, -1, "")
    app.SetTopWindow(LotoMania)
    LotoMania.Show()
    app.MainLoop()
